<?php

namespace Database\Seeders;

use App\Models\City;
use App\Models\FloridaCity;
use Illuminate\Database\Seeder;

class FloridaCitySeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        City::where('state_id','3930')->delete();
        City::insert([
            ["state_id"=>"3930", "status"=> "active","name"=>'Alachua, FL'],
            ["state_id"=>"3930", "status"=> "active","name"=>'Alford, FL'],
            ["state_id"=>"3930", "status"=> "active","name"=>'Altamonte Springs, FL'],
            ["state_id"=>"3930", "status"=> "active","name"=>'Altha, FL'],
            ["state_id"=>"3930", "status"=> "active","name"=>'Alva, FL'],
            ["state_id"=>"3930", "status"=> "active","name"=>'Anna Maria, FL'],
            ["state_id"=>"3930", "status"=> "active","name"=>'Apalachicola, FL'],
            ["state_id"=>"3930", "status"=> "active","name"=>'Apollo Beach, FL'],
            ["state_id"=>"3930", "status"=> "active","name"=>'Apopka, FL'],
            ["state_id"=>"3930", "status"=> "active","name"=>'Arcadia, FL'],
            ["state_id"=>"3930", "status"=> "active","name"=>'Archer, FL'],
            ["state_id"=>"3930", "status"=> "active","name"=>'Astatula, FL'],
            ["state_id"=>"3930", "status"=> "active","name"=>'Astor, FL'],
            ["state_id"=>"3930", "status"=> "active","name"=>'Atlantic Beach, FL'],
            ["state_id"=>"3930", "status"=> "active","name"=>'Auburndale, FL'],
            ["state_id"=>"3930", "status"=> "active","name"=>'Avon Park, FL'],
            ["state_id"=>"3930", "status"=> "active","name"=>'Babson Park, FL'],
            ["state_id"=>"3930", "status"=> "active","name"=>'Bagdad, FL'],
            ["state_id"=>"3930", "status"=> "active","name"=>'Bartow, FL'],
            ["state_id"=>"3930", "status"=> "active","name"=>'Bay Pines, FL'],
            ["state_id"=>"3930", "status"=> "active","name"=>'Bell, FL'],
            ["state_id"=>"3930", "status"=> "active","name"=>'Belle Glade, FL'],
            ["state_id"=>"3930", "status"=> "active","name"=>'Belleair Beach, FL'],
            ["state_id"=>"3930", "status"=> "active","name"=>'Belleview, FL'],
            ["state_id"=>"3930", "status"=> "active","name"=>'Beverly Hills, FL'],
            ["state_id"=>"3930", "status"=> "active","name"=>'Big Pine Key, FL'],
            ["state_id"=>"3930", "status"=> "active","name"=>'Blountstown, FL'],
            ["state_id"=>"3930", "status"=> "active","name"=>'Boca Raton, FL'],
            ["state_id"=>"3930", "status"=> "active","name"=>'Bokeelia, FL'],
            ["state_id"=>"3930", "status"=> "active","name"=>'Bonifay, FL'],
            ["state_id"=>"3930", "status"=> "active","name"=>'Bonita Springs, FL'],
            ["state_id"=>"3930", "status"=> "active","name"=>'Bowling Green, FL'],
            ["state_id"=>"3930", "status"=> "active","name"=>'Boynton Beach, FL'],
            ["state_id"=>"3930", "status"=> "active","name"=>'Bradenton Beach, FL'],
            ["state_id"=>"3930", "status"=> "active","name"=>'Bradenton, FL'],
            ["state_id"=>"3930", "status"=> "active","name"=>'Brandon, FL'],
            ["state_id"=>"3930", "status"=> "active","name"=>'Branford, FL'],
            ["state_id"=>"3930", "status"=> "active","name"=>'Bristol, FL'],
            ["state_id"=>"3930", "status"=> "active","name"=>'Bronson, FL'],
            ["state_id"=>"3930", "status"=> "active","name"=>'Brooker, FL'],
            ["state_id"=>"3930", "status"=> "active","name"=>'Brooksville, FL'],
            ["state_id"=>"3930", "status"=> "active","name"=>'Bunnell, FL'],
            ["state_id"=>"3930", "status"=> "active","name"=>'Bushnell, FL'],
            ["state_id"=>"3930", "status"=> "active","name"=>'Callahan, FL'],
            ["state_id"=>"3930", "status"=> "active","name"=>'Campbellton, FL'],
            ["state_id"=>"3930", "status"=> "active","name"=>'Canal Point, FL'],
            ["state_id"=>"3930", "status"=> "active","name"=>'Cape Canaveral, FL'],
            ["state_id"=>"3930", "status"=> "active","name"=>'Cape Coral, FL'],
            ["state_id"=>"3930", "status"=> "active","name"=>'Captiva, FL'],
            ["state_id"=>"3930", "status"=> "active","name"=>'Carrabelle, FL'],
            ["state_id"=>"3930", "status"=> "active","name"=>'Caryville, FL'],
            ["state_id"=>"3930", "status"=> "active","name"=>'Casselberry, FL'],
            ["state_id"=>"3930", "status"=> "active","name"=>'Cedar Key, FL'],
            ["state_id"=>"3930", "status"=> "active","name"=>'Center Hill, FL'],
            ["state_id"=>"3930", "status"=> "active","name"=>'Century, FL'],
            ["state_id"=>"3930", "status"=> "active","name"=>'Chattahoochee, FL'],
            ["state_id"=>"3930", "status"=> "active","name"=>'ChieFL and, FL'],
            ["state_id"=>"3930", "status"=> "active","name"=>'Chipley, FL'],
            ["state_id"=>"3930", "status"=> "active","name"=>'Chokoloskee, FL'],
            ["state_id"=>"3930", "status"=> "active","name"=>'Christmas, FL'],
            ["state_id"=>"3930", "status"=> "active","name"=>'Clearwater, FL'],
            ["state_id"=>"3930", "status"=> "active","name"=>'Clermont, FL'],
            ["state_id"=>"3930", "status"=> "active","name"=>'Clewiston, FL'],
            ["state_id"=>"3930", "status"=> "active","name"=>'Cocoa Beach, FL'],
            ["state_id"=>"3930", "status"=> "active","name"=>'Cocoa, FL'],
            ["state_id"=>"3930", "status"=> "active","name"=>'Coleman, FL'],
            ["state_id"=>"3930", "status"=> "active","name"=>'Cortez, FL'],
            ["state_id"=>"3930", "status"=> "active","name"=>'Cottondale, FL'],
            ["state_id"=>"3930", "status"=> "active","name"=>'Crescent City, FL'],
            ["state_id"=>"3930", "status"=> "active","name"=>'Crestview, FL'],
            ["state_id"=>"3930", "status"=> "active","name"=>'Cross City, FL'],
            ["state_id"=>"3930", "status"=> "active","name"=>'Crystal River, FL'],
            ["state_id"=>"3930", "status"=> "active","name"=>'Crystal Springs, FL'],
            ["state_id"=>"3930", "status"=> "active","name"=>'Cypress, FL'],
            ["state_id"=>"3930", "status"=> "active","name"=>'Dade City, FL'],
            ["state_id"=>"3930", "status"=> "active","name"=>'Dania, FL'],
            ["state_id"=>"3930", "status"=> "active","name"=>'Davenport, FL'],
            ["state_id"=>"3930", "status"=> "active","name"=>'Daytona Beach, FL'],
            ["state_id"=>"3930", "status"=> "active","name"=>'De Leon Springs, FL'],
            ["state_id"=>"3930", "status"=> "active","name"=>'Debary, FL'],
            ["state_id"=>"3930", "status"=> "active","name"=>'Deerfield Beach, FL'],
            ["state_id"=>"3930", "status"=> "active","name"=>'Deland, FL'],
            ["state_id"=>"3930", "status"=> "active","name"=>'Delray Beach, FL'],
            ["state_id"=>"3930", "status"=> "active","name"=>'Deltona, FL'],
            ["state_id"=>"3930", "status"=> "active","name"=>'Destin, FL'],
            ["state_id"=>"3930", "status"=> "active","name"=>'Dover, FL'],
            ["state_id"=>"3930", "status"=> "active","name"=>'Dundee, FL'],
            ["state_id"=>"3930", "status"=> "active","name"=>'Dunedin, FL'],
            ["state_id"=>"3930", "status"=> "active","name"=>'Dunnellon, FL'],
            ["state_id"=>"3930", "status"=> "active","name"=>'Eagle Lake, FL'],
            ["state_id"=>"3930", "status"=> "active","name"=>'East Palatka, FL'],
            ["state_id"=>"3930", "status"=> "active","name"=>'Eastpoint, FL'],
            ["state_id"=>"3930", "status"=> "active","name"=>'Ebro, FL'],
            ["state_id"=>"3930", "status"=> "active","name"=>'Edgewater, FL'],
            ["state_id"=>"3930", "status"=> "active","name"=>'Eglin Afb, FL'],
            ["state_id"=>"3930", "status"=> "active","name"=>'Elfers, FL'],
            ["state_id"=>"3930", "status"=> "active","name"=>'Ellenton, FL'],
            ["state_id"=>"3930", "status"=> "active","name"=>'Englewood, FL'],
            ["state_id"=>"3930", "status"=> "active","name"=>'Estero, FL'],
            ["state_id"=>"3930", "status"=> "active","name"=>'Eustis, FL'],
            ["state_id"=>"3930", "status"=> "active","name"=>'Fellsmere, FL'],
            ["state_id"=>"3930", "status"=> "active","name"=>'Fernandina Beach, FL'],
            ["state_id"=>"3930", "status"=> "active","name"=>'Ferndale, FL'],
            ["state_id"=>"3930", "status"=> "active","name"=>'FLagler Beach, FL'],
            ["state_id"=>"3930", "status"=> "active","name"=>'FLoral City, FL'],
            ["state_id"=>"3930", "status"=> "active","name"=>'Fort Lauderdale, FL'],
            ["state_id"=>"3930", "status"=> "active","name"=>'Fort Meade, FL'],
            ["state_id"=>"3930", "status"=> "active","name"=>'Fort Myers Beach, FL'],
            ["state_id"=>"3930", "status"=> "active","name"=>'Fort Myers, FL'],
            ["state_id"=>"3930", "status"=> "active","name"=>'Fort Pierce, FL'],
            ["state_id"=>"3930", "status"=> "active","name"=>'Fort Walton Beach, FL'],
            ["state_id"=>"3930", "status"=> "active","name"=>'Fort White, FL'],
            ["state_id"=>"3930", "status"=> "active","name"=>'Freeport, FL'],
            ["state_id"=>"3930", "status"=> "active","name"=>'Frostproof, FL'],
            ["state_id"=>"3930", "status"=> "active","name"=>'Fruitland Park, FL'],
            ["state_id"=>"3930", "status"=> "active","name"=>'Gainesville, FL'],
            ["state_id"=>"3930", "status"=> "active","name"=>'Geneva, FL'],
            ["state_id"=>"3930", "status"=> "active","name"=>'Gibsonton, FL'],
            ["state_id"=>"3930", "status"=> "active","name"=>'Glen Saint Mary, FL'],
            ["state_id"=>"3930", "status"=> "active","name"=>'Goldenrod, FL'],
            ["state_id"=>"3930", "status"=> "active","name"=>'Gonzalez, FL'],
            ["state_id"=>"3930", "status"=> "active","name"=>'Goodland, FL'],
            ["state_id"=>"3930", "status"=> "active","name"=>'Gotha, FL'],
            ["state_id"=>"3930", "status"=> "active","name"=>'Graceville, FL'],
            ["state_id"=>"3930", "status"=> "active","name"=>'Grand Ridge, FL'],
            ["state_id"=>"3930", "status"=> "active","name"=>'Green Cove Springs, FL'],
            ["state_id"=>"3930", "status"=> "active","name"=>'Greensboro, FL'],
            ["state_id"=>"3930", "status"=> "active","name"=>'Greenville, FL'],
            ["state_id"=>"3930", "status"=> "active","name"=>'Greenwood, FL'],
            ["state_id"=>"3930", "status"=> "active","name"=>'Gretna, FL'],
            ["state_id"=>"3930", "status"=> "active","name"=>'Groveland, FL'],
            ["state_id"=>"3930", "status"=> "active","name"=>'Gulf Breeze, FL'],
            ["state_id"=>"3930", "status"=> "active","name"=>'Haines City, FL'],
            ["state_id"=>"3930", "status"=> "active","name"=>'Hallandale, FL'],
            ["state_id"=>"3930", "status"=> "active","name"=>'Hampton, FL'],
            ["state_id"=>"3930", "status"=> "active","name"=>'Hastings, FL'],
            ["state_id"=>"3930", "status"=> "active","name"=>'Havana, FL'],
            ["state_id"=>"3930", "status"=> "active","name"=>'Hawthorne, FL'],
            ["state_id"=>"3930", "status"=> "active","name"=>'Hernando, FL'],
            ["state_id"=>"3930", "status"=> "active","name"=>'Hialeah, FL'],
            ["state_id"=>"3930", "status"=> "active","name"=>'High Springs, FL'],
            ["state_id"=>"3930", "status"=> "active","name"=>'Highland City, FL'],
            ["state_id"=>"3930", "status"=> "active","name"=>'Hilliard, FL'],
            ["state_id"=>"3930", "status"=> "active","name"=>'Hobe Sound, FL'],
            ["state_id"=>"3930", "status"=> "active","name"=>'Holiday, FL'],
            ["state_id"=>"3930", "status"=> "active","name"=>'Hollywood, FL'],
            ["state_id"=>"3930", "status"=> "active","name"=>'Holmes Beach, FL'],
            ["state_id"=>"3930", "status"=> "active","name"=>'Homestead, FL'],
            ["state_id"=>"3930", "status"=> "active","name"=>'Homosassa Springs, FL'],
            ["state_id"=>"3930", "status"=> "active","name"=>'Homosassa, FL'],
            ["state_id"=>"3930", "status"=> "active","name"=>'Horseshoe Beach, FL'],
            ["state_id"=>"3930", "status"=> "active","name"=>'Howey In The Hills, FL'],
            ["state_id"=>"3930", "status"=> "active","name"=>'Hudson, FL'],
            ["state_id"=>"3930", "status"=> "active","name"=>'Immokalee, FL'],
            ["state_id"=>"3930", "status"=> "active","name"=>'Indialantic, FL'],
            ["state_id"=>"3930", "status"=> "active","name"=>'Indian Rocks Beach, FL'],
            ["state_id"=>"3930", "status"=> "active","name"=>'Indiantown, FL'],
            ["state_id"=>"3930", "status"=> "active","name"=>'Inglis, FL'],
            ["state_id"=>"3930", "status"=> "active","name"=>'Interlachen, FL'],
            ["state_id"=>"3930", "status"=> "active","name"=>'Inverness, FL'],
            ["state_id"=>"3930", "status"=> "active","name"=>'Islamorada, FL'],
            ["state_id"=>"3930", "status"=> "active","name"=>'Jacksonville Beach, FL'],
            ["state_id"=>"3930", "status"=> "active","name"=>'Jacksonville, FL'],
            ["state_id"=>"3930", "status"=> "active","name"=>'Jasper, FL'],
            ["state_id"=>"3930", "status"=> "active","name"=>'Jay, FL'],
            ["state_id"=>"3930", "status"=> "active","name"=>'Jennings, FL'],
            ["state_id"=>"3930", "status"=> "active","name"=>'Jensen Beach, FL'],
            ["state_id"=>"3930", "status"=> "active","name"=>'Jupiter, FL'],
            ["state_id"=>"3930", "status"=> "active","name"=>'Kathleen, FL'],
            ["state_id"=>"3930", "status"=> "active","name"=>'Key Biscayne, FL'],
            ["state_id"=>"3930", "status"=> "active","name"=>'Key Colony Beach, FL'],
            ["state_id"=>"3930", "status"=> "active","name"=>'Key Largo, FL'],
            ["state_id"=>"3930", "status"=> "active","name"=>'Key West, FL'],
            ["state_id"=>"3930", "status"=> "active","name"=>'Keystone Heights, FL'],
            ["state_id"=>"3930", "status"=> "active","name"=>'Kissimmee, FL'],
            ["state_id"=>"3930", "status"=> "active","name"=>'Labelle, FL'],
            ["state_id"=>"3930", "status"=> "active","name"=>'Lacoochee, FL'],
            ["state_id"=>"3930", "status"=> "active","name"=>'Lady Lake, FL'],
            ["state_id"=>"3930", "status"=> "active","name"=>'Lake Alfred, FL'],
            ["state_id"=>"3930", "status"=> "active","name"=>'Lake Butler, FL'],
            ["state_id"=>"3930", "status"=> "active","name"=>'Lake City, FL'],
            ["state_id"=>"3930", "status"=> "active","name"=>'Lake Hamilton, FL'],
            ["state_id"=>"3930", "status"=> "active","name"=>'Lake Helen, FL'],
            ["state_id"=>"3930", "status"=> "active","name"=>'Lake Mary, FL'],
            ["state_id"=>"3930", "status"=> "active","name"=>'Lake Panasoffkee, FL'],
            ["state_id"=>"3930", "status"=> "active","name"=>'Lake Placid, FL'],
            ["state_id"=>"3930", "status"=> "active","name"=>'Lake Wales, FL'],
            ["state_id"=>"3930", "status"=> "active","name"=>'Lake Worth, FL'],
            ["state_id"=>"3930", "status"=> "active","name"=>'Lakeland, FL'],
            ["state_id"=>"3930", "status"=> "active","name"=>'Land O Lakes, FL'],
            ["state_id"=>"3930", "status"=> "active","name"=>'Largo, FL'],
            ["state_id"=>"3930", "status"=> "active","name"=>'Laurel Hill, FL'],
            ["state_id"=>"3930", "status"=> "active","name"=>'Laurel, FL'],
            ["state_id"=>"3930", "status"=> "active","name"=>'Lawtey, FL'],
            ["state_id"=>"3930", "status"=> "active","name"=>'Lecanto, FL'],
            ["state_id"=>"3930", "status"=> "active","name"=>'Lee, FL'],
            ["state_id"=>"3930", "status"=> "active","name"=>'Leesburg, FL'],
            ["state_id"=>"3930", "status"=> "active","name"=>'Lehigh Acres, FL'],
            ["state_id"=>"3930", "status"=> "active","name"=>'Live Oak, FL'],
            ["state_id"=>"3930", "status"=> "active","name"=>'Longboat Key, FL'],
            ["state_id"=>"3930", "status"=> "active","name"=>'Longwood, FL'],
            ["state_id"=>"3930", "status"=> "active","name"=>'Loughman, FL'],
            ["state_id"=>"3930", "status"=> "active","name"=>'Lutz, FL'],
            ["state_id"=>"3930", "status"=> "active","name"=>'Lynn Haven, FL'],
            ["state_id"=>"3930", "status"=> "active","name"=>'Macclenny, FL'],
            ["state_id"=>"3930", "status"=> "active","name"=>'Madison, FL'],
            ["state_id"=>"3930", "status"=> "active","name"=>'Maitland, FL'],
            ["state_id"=>"3930", "status"=> "active","name"=>'Malabar, FL'],
            ["state_id"=>"3930", "status"=> "active","name"=>'Malone, FL'],
            ["state_id"=>"3930", "status"=> "active","name"=>'Mango, FL'],
            ["state_id"=>"3930", "status"=> "active","name"=>'Marathon, FL'],
            ["state_id"=>"3930", "status"=> "active","name"=>'Marco Island, FL'],
            ["state_id"=>"3930", "status"=> "active","name"=>'Marianna, FL'],
            ["state_id"=>"3930", "status"=> "active","name"=>'Mary Esther, FL'],
            ["state_id"=>"3930", "status"=> "active","name"=>'Mascotte, FL'],
            ["state_id"=>"3930", "status"=> "active","name"=>'Mayo, FL'],
            ["state_id"=>"3930", "status"=> "active","name"=>'Mc Intosh, FL'],
            ["state_id"=>"3930", "status"=> "active","name"=>'Melbourne Beach, FL'],
            ["state_id"=>"3930", "status"=> "active","name"=>'Melbourne, FL'],
            ["state_id"=>"3930", "status"=> "active","name"=>'Merritt Island, FL'],
            ["state_id"=>"3930", "status"=> "active","name"=>'Mexico Beach, FL'],
            ["state_id"=>"3930", "status"=> "active","name"=>'Miami Beach, FL'],
            ["state_id"=>"3930", "status"=> "active","name"=>'Miami, FL'],
            ["state_id"=>"3930", "status"=> "active","name"=>'Micanopy, FL'],
            ["state_id"=>"3930", "status"=> "active","name"=>'Middleburg, FL'],
            ["state_id"=>"3930", "status"=> "active","name"=>'Midway, FL'],
            ["state_id"=>"3930", "status"=> "active","name"=>'Milton, FL'],
            ["state_id"=>"3930", "status"=> "active","name"=>'Mims, FL'],
            ["state_id"=>"3930", "status"=> "active","name"=>'Minneola, FL'],
            ["state_id"=>"3930", "status"=> "active","name"=>'Miramar Beach, FL'],
            ["state_id"=>"3930", "status"=> "active","name"=>'Molino, FL'],
            ["state_id"=>"3930", "status"=> "active","name"=>'Monticello, FL'],
            ["state_id"=>"3930", "status"=> "active","name"=>'Montverde, FL'],
            ["state_id"=>"3930", "status"=> "active","name"=>'Moore Haven, FL'],
            ["state_id"=>"3930", "status"=> "active","name"=>'Mount Dora, FL'],
            ["state_id"=>"3930", "status"=> "active","name"=>'Mulberry, FL'],
            ["state_id"=>"3930", "status"=> "active","name"=>'Naples, FL'],
            ["state_id"=>"3930", "status"=> "active","name"=>'Neptune Beach, FL'],
            ["state_id"=>"3930", "status"=> "active","name"=>'New Port Richey, FL'],
            ["state_id"=>"3930", "status"=> "active","name"=>'New Smyrna Beach, FL'],
            ["state_id"=>"3930", "status"=> "active","name"=>'Newberry, FL'],
            ["state_id"=>"3930", "status"=> "active","name"=>'Niceville, FL'],
            ["state_id"=>"3930", "status"=> "active","name"=>'Nokomis, FL'],
            ["state_id"=>"3930", "status"=> "active","name"=>'Noma, FL'],
            ["state_id"=>"3930", "status"=> "active","name"=>'North Fort Myers, FL'],
            ["state_id"=>"3930", "status"=> "active","name"=>'North Miami Beach, FL'],
            ["state_id"=>"3930", "status"=> "active","name"=>'North Palm Beach, FL'],
            ["state_id"=>"3930", "status"=> "active","name"=>'North Port, FL'],
            ["state_id"=>"3930", "status"=> "active","name"=>'Oak Hill, FL'],
            ["state_id"=>"3930", "status"=> "active","name"=>'Oakland, FL'],
            ["state_id"=>"3930", "status"=> "active","name"=>'Ocala, FL'],
            ["state_id"=>"3930", "status"=> "active","name"=>'Ocoee, FL'],
            ["state_id"=>"3930", "status"=> "active","name"=>'Odessa, FL'],
            ["state_id"=>"3930", "status"=> "active","name"=>'Okahumpka, FL'],
            ["state_id"=>"3930", "status"=> "active","name"=>'Okeechobee, FL'],
            ["state_id"=>"3930", "status"=> "active","name"=>'Oldsmar, FL'],
            ["state_id"=>"3930", "status"=> "active","name"=>'Opa Locka, FL'],
            ["state_id"=>"3930", "status"=> "active","name"=>'Orange City, FL'],
            ["state_id"=>"3930", "status"=> "active","name"=>'Orange Park, FL'],
            ["state_id"=>"3930", "status"=> "active","name"=>'Orlando, FL'],
            ["state_id"=>"3930", "status"=> "active","name"=>'Ormond Beach, FL'],
            ["state_id"=>"3930", "status"=> "active","name"=>'Osprey, FL'],
            ["state_id"=>"3930", "status"=> "active","name"=>'Oviedo, FL'],
            ["state_id"=>"3930", "status"=> "active","name"=>'Pahokee, FL'],
            ["state_id"=>"3930", "status"=> "active","name"=>'Paisley, FL'],
            ["state_id"=>"3930", "status"=> "active","name"=>'Palatka, FL'],
            ["state_id"=>"3930", "status"=> "active","name"=>'Palm Bay, FL'],
            ["state_id"=>"3930", "status"=> "active","name"=>'Palm Beach Gardens, FL'],
            ["state_id"=>"3930", "status"=> "active","name"=>'Palm Beach, FL'],
            ["state_id"=>"3930", "status"=> "active","name"=>'Palm City, FL'],
            ["state_id"=>"3930", "status"=> "active","name"=>'Palm Coast, FL'],
            ["state_id"=>"3930", "status"=> "active","name"=>'Palm Harbor, FL'],
            ["state_id"=>"3930", "status"=> "active","name"=>'Palmetto, FL'],
            ["state_id"=>"3930", "status"=> "active","name"=>'Panama City Beach, FL'],
            ["state_id"=>"3930", "status"=> "active","name"=>'Panama City, FL'],
            ["state_id"=>"3930", "status"=> "active","name"=>'Paxton, FL'],
            ["state_id"=>"3930", "status"=> "active","name"=>'Pembroke Pines, FL'],
            ["state_id"=>"3930", "status"=> "active","name"=>'Penney Farms, FL'],
            ["state_id"=>"3930", "status"=> "active","name"=>'Pensacola, FL'],
            ["state_id"=>"3930", "status"=> "active","name"=>'Perry, FL'],
            ["state_id"=>"3930", "status"=> "active","name"=>'Pierson, FL'],
            ["state_id"=>"3930", "status"=> "active","name"=>'Pineland, FL'],
            ["state_id"=>"3930", "status"=> "active","name"=>'Pinellas Park, FL'],
            ["state_id"=>"3930", "status"=> "active","name"=>'Placida, FL'],
            ["state_id"=>"3930", "status"=> "active","name"=>'Plant City, FL'],
            ["state_id"=>"3930", "status"=> "active","name"=>'Polk City, FL'],
            ["state_id"=>"3930", "status"=> "active","name"=>'Pomona Park, FL'],
            ["state_id"=>"3930", "status"=> "active","name"=>'Pompano Beach, FL'],
            ["state_id"=>"3930", "status"=> "active","name"=>'Ponce De Leon, FL'],
            ["state_id"=>"3930", "status"=> "active","name"=>'Port Charlotte, FL'],
            ["state_id"=>"3930", "status"=> "active","name"=>'Port Orange, FL'],
            ["state_id"=>"3930", "status"=> "active","name"=>'Port Richey, FL'],
            ["state_id"=>"3930", "status"=> "active","name"=>'Port Saint Joe, FL'],
            ["state_id"=>"3930", "status"=> "active","name"=>'Port Saint Lucie, FL'],
            ["state_id"=>"3930", "status"=> "active","name"=>'Port Salerno, FL'],
            ["state_id"=>"3930", "status"=> "active","name"=>'Punta Gorda, FL'],
            ["state_id"=>"3930", "status"=> "active","name"=>'Quincy, FL'],
            ["state_id"=>"3930", "status"=> "active","name"=>'Reddick, FL'],
            ["state_id"=>"3930", "status"=> "active","name"=>'Riverview, FL'],
            ["state_id"=>"3930", "status"=> "active","name"=>'Rockledge, FL'],
            ["state_id"=>"3930", "status"=> "active","name"=>'Roseland, FL'],
            ["state_id"=>"3930", "status"=> "active","name"=>'Rotonda West, FL'],
            ["state_id"=>"3930", "status"=> "active","name"=>'Ruskin, FL'],
            ["state_id"=>"3930", "status"=> "active","name"=>'Safety Harbor, FL'],
            ["state_id"=>"3930", "status"=> "active","name"=>'San Antonio, FL'],
            ["state_id"=>"3930", "status"=> "active","name"=>'Sanford, FL'],
            ["state_id"=>"3930", "status"=> "active","name"=>'Sanibel, FL'],
            ["state_id"=>"3930", "status"=> "active","name"=>'Sarasota, FL'],
            ["state_id"=>"3930", "status"=> "active","name"=>'Satellite Beach, FL'],
            ["state_id"=>"3930", "status"=> "active","name"=>'Sebastian, FL'],
            ["state_id"=>"3930", "status"=> "active","name"=>'Sebring, FL'],
            ["state_id"=>"3930", "status"=> "active","name"=>'Seffner, FL'],
            ["state_id"=>"3930", "status"=> "active","name"=>'Seminole, FL'],
            ["state_id"=>"3930", "status"=> "active","name"=>'Shalimar, FL'],
            ["state_id"=>"3930", "status"=> "active","name"=>'Sharpes, FL'],
            ["state_id"=>"3930", "status"=> "active","name"=>'Silver Springs, FL'],
            ["state_id"=>"3930", "status"=> "active","name"=>'Sneads, FL'],
            ["state_id"=>"3930", "status"=> "active","name"=>'Sopchoppy, FL'],
            ["state_id"=>"3930", "status"=> "active","name"=>'Sorrento, FL'],
            ["state_id"=>"3930", "status"=> "active","name"=>'South Bay, FL'],
            ["state_id"=>"3930", "status"=> "active","name"=>'Spring Hill, FL'],
            ["state_id"=>"3930", "status"=> "active","name"=>'Starke, FL'],
            ["state_id"=>"3930", "status"=> "active","name"=>'Stuart, FL'],
            ["state_id"=>"3930", "status"=> "active","name"=>'Tallahassee, FL'],
            ["state_id"=>"3930", "status"=> "active","name"=>'Tampa, FL'],
            ["state_id"=>"3930", "status"=> "active","name"=>'Tangerine, FL'],
            ["state_id"=>"3930", "status"=> "active","name"=>'Tarpon Springs, FL'],
            ["state_id"=>"3930", "status"=> "active","name"=>'Tavares, FL'],
            ["state_id"=>"3930", "status"=> "active","name"=>'Tavernier, FL'],
            ["state_id"=>"3930", "status"=> "active","name"=>'Thonotosassa, FL'],
            ["state_id"=>"3930", "status"=> "active","name"=>'Titusville, FL'],
            ["state_id"=>"3930", "status"=> "active","name"=>'Trenton, FL'],
            ["state_id"=>"3930", "status"=> "active","name"=>'Umatilla, FL'],
            ["state_id"=>"3930", "status"=> "active","name"=>'Valparaiso, FL'],
            ["state_id"=>"3930", "status"=> "active","name"=>'Valrico, FL'],
            ["state_id"=>"3930", "status"=> "active","name"=>'Venice, FL'],
            ["state_id"=>"3930", "status"=> "active","name"=>'Vernon, FL'],
            ["state_id"=>"3930", "status"=> "active","name"=>'Vero Beach, FL'],
            ["state_id"=>"3930", "status"=> "active","name"=>'Wabasso, FL'],
            ["state_id"=>"3930", "status"=> "active","name"=>'Waldo, FL'],
            ["state_id"=>"3930", "status"=> "active","name"=>'Wauchula, FL'],
            ["state_id"=>"3930", "status"=> "active","name"=>'Wausau, FL'],
            ["state_id"=>"3930", "status"=> "active","name"=>'Waverly, FL'],
            ["state_id"=>"3930", "status"=> "active","name"=>'Webster, FL'],
            ["state_id"=>"3930", "status"=> "active","name"=>'Welaka, FL'],
            ["state_id"=>"3930", "status"=> "active","name"=>'West Palm Beach, FL'],
            ["state_id"=>"3930", "status"=> "active","name"=>'Westville, FL'],
            ["state_id"=>"3930", "status"=> "active","name"=>'Wewahitchka, FL'],
            ["state_id"=>"3930", "status"=> "active","name"=>'White Springs, FL'],
            ["state_id"=>"3930", "status"=> "active","name"=>'Wildwood, FL'],
            ["state_id"=>"3930", "status"=> "active","name"=>'Williston, FL'],
            ["state_id"=>"3930", "status"=> "active","name"=>'Wimauma, FL'],
            ["state_id"=>"3930", "status"=> "active","name"=>'Windermere, FL'],
            ["state_id"=>"3930", "status"=> "active","name"=>'Winter Beach, FL'],
            ["state_id"=>"3930", "status"=> "active","name"=>'Winter Garden, FL'],
            ["state_id"=>"3930", "status"=> "active","name"=>'Winter Haven, FL'],
            ["state_id"=>"3930", "status"=> "active","name"=>'Winter Park, FL'],
            ["state_id"=>"3930", "status"=> "active","name"=>'Winter Springs, FL'],
            ["state_id"=>"3930", "status"=> "active","name"=>'Woodville, FL'],
            ["state_id"=>"3930", "status"=> "active","name"=>'Yalaha, FL'],
            ["state_id"=>"3930", "status"=> "active","name"=>'Yankeetown, FL'],
            ["state_id"=>"3930", "status"=> "active","name"=>'Yulee, FL'],
            ["state_id"=>"3930", "status"=> "active","name"=>'Zellwood, FL'],
            ["state_id"=>"3930", "status"=> "active","name"=>'Zephyrhills, FL'],
            ["state_id"=>"3930", "status"=> "active","name"=>'Zolfo Springs, FL'],
        ]);
        FloridaCity::insert([
            ['name'=>'Alachua, FL'],
            ['name'=>'Alford, FL'],
            ['name'=>'Altamonte Springs, FL'],
            ['name'=>'Altha, FL'],
            ['name'=>'Alva, FL'],
            ['name'=>'Anna Maria, FL'],
            ['name'=>'Apalachicola, FL'],
            ['name'=>'Apollo Beach, FL'],
            ['name'=>'Apopka, FL'],
            ['name'=>'Arcadia, FL'],
            ['name'=>'Archer, FL'],
            ['name'=>'Astatula, FL'],
            ['name'=>'Astor, FL'],
            ['name'=>'Atlantic Beach, FL'],
            ['name'=>'Auburndale, FL'],
            ['name'=>'Avon Park, FL'],
            ['name'=>'Babson Park, FL'],
            ['name'=>'Bagdad, FL'],
            ['name'=>'Bartow, FL'],
            ['name'=>'Bay Pines, FL'],
            ['name'=>'Bell, FL'],
            ['name'=>'Belle Glade, FL'],
            ['name'=>'Belleair Beach, FL'],
            ['name'=>'Belleview, FL'],
            ['name'=>'Beverly Hills, FL'],
            ['name'=>'Big Pine Key, FL'],
            ['name'=>'Blountstown, FL'],
            ['name'=>'Boca Raton, FL'],
            ['name'=>'Bokeelia, FL'],
            ['name'=>'Bonifay, FL'],
            ['name'=>'Bonita Springs, FL'],
            ['name'=>'Bowling Green, FL'],
            ['name'=>'Boynton Beach, FL'],
            ['name'=>'Bradenton Beach, FL'],
            ['name'=>'Bradenton, FL'],
            ['name'=>'Brandon, FL'],
            ['name'=>'Branford, FL'],
            ['name'=>'Bristol, FL'],
            ['name'=>'Bronson, FL'],
            ['name'=>'Brooker, FL'],
            ['name'=>'Brooksville, FL'],
            ['name'=>'Bunnell, FL'],
            ['name'=>'Bushnell, FL'],
            ['name'=>'Callahan, FL'],
            ['name'=>'Campbellton, FL'],
            ['name'=>'Canal Point, FL'],
            ['name'=>'Cape Canaveral, FL'],
            ['name'=>'Cape Coral, FL'],
            ['name'=>'Captiva, FL'],
            ['name'=>'Carrabelle, FL'],
            ['name'=>'Caryville, FL'],
            ['name'=>'Casselberry, FL'],
            ['name'=>'Cedar Key, FL'],
            ['name'=>'Center Hill, FL'],
            ['name'=>'Century, FL'],
            ['name'=>'Chattahoochee, FL'],
            ['name'=>'ChieFL and, FL'],
            ['name'=>'Chipley, FL'],
            ['name'=>'Chokoloskee, FL'],
            ['name'=>'Christmas, FL'],
            ['name'=>'Clearwater, FL'],
            ['name'=>'Clermont, FL'],
            ['name'=>'Clewiston, FL'],
            ['name'=>'Cocoa Beach, FL'],
            ['name'=>'Cocoa, FL'],
            ['name'=>'Coleman, FL'],
            ['name'=>'Cortez, FL'],
            ['name'=>'Cottondale, FL'],
            ['name'=>'Crescent City, FL'],
            ['name'=>'Crestview, FL'],
            ['name'=>'Cross City, FL'],
            ['name'=>'Crystal River, FL'],
            ['name'=>'Crystal Springs, FL'],
            ['name'=>'Cypress, FL'],
            ['name'=>'Dade City, FL'],
            ['name'=>'Dania, FL'],
            ['name'=>'Davenport, FL'],
            ['name'=>'Daytona Beach, FL'],
            ['name'=>'De Leon Springs, FL'],
            ['name'=>'Debary, FL'],
            ['name'=>'Deerfield Beach, FL'],
            ['name'=>'Deland, FL'],
            ['name'=>'Delray Beach, FL'],
            ['name'=>'Deltona, FL'],
            ['name'=>'Destin, FL'],
            ['name'=>'Dover, FL'],
            ['name'=>'Dundee, FL'],
            ['name'=>'Dunedin, FL'],
            ['name'=>'Dunnellon, FL'],
            ['name'=>'Eagle Lake, FL'],
            ['name'=>'East Palatka, FL'],
            ['name'=>'Eastpoint, FL'],
            ['name'=>'Ebro, FL'],
            ['name'=>'Edgewater, FL'],
            ['name'=>'Eglin Afb, FL'],
            ['name'=>'Elfers, FL'],
            ['name'=>'Ellenton, FL'],
            ['name'=>'Englewood, FL'],
            ['name'=>'Estero, FL'],
            ['name'=>'Eustis, FL'],
            ['name'=>'Fellsmere, FL'],
            ['name'=>'Fernandina Beach, FL'],
            ['name'=>'Ferndale, FL'],
            ['name'=>'FLagler Beach, FL'],
            ['name'=>'FLoral City, FL'],
            ['name'=>'Fort Lauderdale, FL'],
            ['name'=>'Fort Meade, FL'],
            ['name'=>'Fort Myers Beach, FL'],
            ['name'=>'Fort Myers, FL'],
            ['name'=>'Fort Pierce, FL'],
            ['name'=>'Fort Walton Beach, FL'],
            ['name'=>'Fort White, FL'],
            ['name'=>'Freeport, FL'],
            ['name'=>'Frostproof, FL'],
            ['name'=>'Fruitland Park, FL'],
            ['name'=>'Gainesville, FL'],
            ['name'=>'Geneva, FL'],
            ['name'=>'Gibsonton, FL'],
            ['name'=>'Glen Saint Mary, FL'],
            ['name'=>'Goldenrod, FL'],
            ['name'=>'Gonzalez, FL'],
            ['name'=>'Goodland, FL'],
            ['name'=>'Gotha, FL'],
            ['name'=>'Graceville, FL'],
            ['name'=>'Grand Ridge, FL'],
            ['name'=>'Green Cove Springs, FL'],
            ['name'=>'Greensboro, FL'],
            ['name'=>'Greenville, FL'],
            ['name'=>'Greenwood, FL'],
            ['name'=>'Gretna, FL'],
            ['name'=>'Groveland, FL'],
            ['name'=>'Gulf Breeze, FL'],
            ['name'=>'Haines City, FL'],
            ['name'=>'Hallandale, FL'],
            ['name'=>'Hampton, FL'],
            ['name'=>'Hastings, FL'],
            ['name'=>'Havana, FL'],
            ['name'=>'Hawthorne, FL'],
            ['name'=>'Hernando, FL'],
            ['name'=>'Hialeah, FL'],
            ['name'=>'High Springs, FL'],
            ['name'=>'Highland City, FL'],
            ['name'=>'Hilliard, FL'],
            ['name'=>'Hobe Sound, FL'],
            ['name'=>'Holiday, FL'],
            ['name'=>'Hollywood, FL'],
            ['name'=>'Holmes Beach, FL'],
            ['name'=>'Homestead, FL'],
            ['name'=>'Homosassa Springs, FL'],
            ['name'=>'Homosassa, FL'],
            ['name'=>'Horseshoe Beach, FL'],
            ['name'=>'Howey In The Hills, FL'],
            ['name'=>'Hudson, FL'],
            ['name'=>'Immokalee, FL'],
            ['name'=>'Indialantic, FL'],
            ['name'=>'Indian Rocks Beach, FL'],
            ['name'=>'Indiantown, FL'],
            ['name'=>'Inglis, FL'],
            ['name'=>'Interlachen, FL'],
            ['name'=>'Inverness, FL'],
            ['name'=>'Islamorada, FL'],
            ['name'=>'Jacksonville Beach, FL'],
            ['name'=>'Jacksonville, FL'],
            ['name'=>'Jasper, FL'],
            ['name'=>'Jay, FL'],
            ['name'=>'Jennings, FL'],
            ['name'=>'Jensen Beach, FL'],
            ['name'=>'Jupiter, FL'],
            ['name'=>'Kathleen, FL'],
            ['name'=>'Key Biscayne, FL'],
            ['name'=>'Key Colony Beach, FL'],
            ['name'=>'Key Largo, FL'],
            ['name'=>'Key West, FL'],
            ['name'=>'Keystone Heights, FL'],
            ['name'=>'Kissimmee, FL'],
            ['name'=>'Labelle, FL'],
            ['name'=>'Lacoochee, FL'],
            ['name'=>'Lady Lake, FL'],
            ['name'=>'Lake Alfred, FL'],
            ['name'=>'Lake Butler, FL'],
            ['name'=>'Lake City, FL'],
            ['name'=>'Lake Hamilton, FL'],
            ['name'=>'Lake Helen, FL'],
            ['name'=>'Lake Mary, FL'],
            ['name'=>'Lake Panasoffkee, FL'],
            ['name'=>'Lake Placid, FL'],
            ['name'=>'Lake Wales, FL'],
            ['name'=>'Lake Worth, FL'],
            ['name'=>'Lakeland, FL'],
            ['name'=>'Land O Lakes, FL'],
            ['name'=>'Largo, FL'],
            ['name'=>'Laurel Hill, FL'],
            ['name'=>'Laurel, FL'],
            ['name'=>'Lawtey, FL'],
            ['name'=>'Lecanto, FL'],
            ['name'=>'Lee, FL'],
            ['name'=>'Leesburg, FL'],
            ['name'=>'Lehigh Acres, FL'],
            ['name'=>'Live Oak, FL'],
            ['name'=>'Longboat Key, FL'],
            ['name'=>'Longwood, FL'],
            ['name'=>'Loughman, FL'],
            ['name'=>'Lutz, FL'],
            ['name'=>'Lynn Haven, FL'],
            ['name'=>'Macclenny, FL'],
            ['name'=>'Madison, FL'],
            ['name'=>'Maitland, FL'],
            ['name'=>'Malabar, FL'],
            ['name'=>'Malone, FL'],
            ['name'=>'Mango, FL'],
            ['name'=>'Marathon, FL'],
            ['name'=>'Marco Island, FL'],
            ['name'=>'Marianna, FL'],
            ['name'=>'Mary Esther, FL'],
            ['name'=>'Mascotte, FL'],
            ['name'=>'Mayo, FL'],
            ['name'=>'Mc Intosh, FL'],
            ['name'=>'Melbourne Beach, FL'],
            ['name'=>'Melbourne, FL'],
            ['name'=>'Merritt Island, FL'],
            ['name'=>'Mexico Beach, FL'],
            ['name'=>'Miami Beach, FL'],
            ['name'=>'Miami, FL'],
            ['name'=>'Micanopy, FL'],
            ['name'=>'Middleburg, FL'],
            ['name'=>'Midway, FL'],
            ['name'=>'Milton, FL'],
            ['name'=>'Mims, FL'],
            ['name'=>'Minneola, FL'],
            ['name'=>'Miramar Beach, FL'],
            ['name'=>'Molino, FL'],
            ['name'=>'Monticello, FL'],
            ['name'=>'Montverde, FL'],
            ['name'=>'Moore Haven, FL'],
            ['name'=>'Mount Dora, FL'],
            ['name'=>'Mulberry, FL'],
            ['name'=>'Naples, FL'],
            ['name'=>'Neptune Beach, FL'],
            ['name'=>'New Port Richey, FL'],
            ['name'=>'New Smyrna Beach, FL'],
            ['name'=>'Newberry, FL'],
            ['name'=>'Niceville, FL'],
            ['name'=>'Nokomis, FL'],
            ['name'=>'Noma, FL'],
            ['name'=>'North Fort Myers, FL'],
            ['name'=>'North Miami Beach, FL'],
            ['name'=>'North Palm Beach, FL'],
            ['name'=>'North Port, FL'],
            ['name'=>'Oak Hill, FL'],
            ['name'=>'Oakland, FL'],
            ['name'=>'Ocala, FL'],
            ['name'=>'Ocoee, FL'],
            ['name'=>'Odessa, FL'],
            ['name'=>'Okahumpka, FL'],
            ['name'=>'Okeechobee, FL'],
            ['name'=>'Oldsmar, FL'],
            ['name'=>'Opa Locka, FL'],
            ['name'=>'Orange City, FL'],
            ['name'=>'Orange Park, FL'],
            ['name'=>'Orlando, FL'],
            ['name'=>'Ormond Beach, FL'],
            ['name'=>'Osprey, FL'],
            ['name'=>'Oviedo, FL'],
            ['name'=>'Pahokee, FL'],
            ['name'=>'Paisley, FL'],
            ['name'=>'Palatka, FL'],
            ['name'=>'Palm Bay, FL'],
            ['name'=>'Palm Beach Gardens, FL'],
            ['name'=>'Palm Beach, FL'],
            ['name'=>'Palm City, FL'],
            ['name'=>'Palm Coast, FL'],
            ['name'=>'Palm Harbor, FL'],
            ['name'=>'Palmetto, FL'],
            ['name'=>'Panama City Beach, FL'],
            ['name'=>'Panama City, FL'],
            ['name'=>'Paxton, FL'],
            ['name'=>'Pembroke Pines, FL'],
            ['name'=>'Penney Farms, FL'],
            ['name'=>'Pensacola, FL'],
            ['name'=>'Perry, FL'],
            ['name'=>'Pierson, FL'],
            ['name'=>'Pineland, FL'],
            ['name'=>'Pinellas Park, FL'],
            ['name'=>'Placida, FL'],
            ['name'=>'Plant City, FL'],
            ['name'=>'Polk City, FL'],
            ['name'=>'Pomona Park, FL'],
            ['name'=>'Pompano Beach, FL'],
            ['name'=>'Ponce De Leon, FL'],
            ['name'=>'Port Charlotte, FL'],
            ['name'=>'Port Orange, FL'],
            ['name'=>'Port Richey, FL'],
            ['name'=>'Port Saint Joe, FL'],
            ['name'=>'Port Saint Lucie, FL'],
            ['name'=>'Port Salerno, FL'],
            ['name'=>'Punta Gorda, FL'],
            ['name'=>'Quincy, FL'],
            ['name'=>'Reddick, FL'],
            ['name'=>'Riverview, FL'],
            ['name'=>'Rockledge, FL'],
            ['name'=>'Roseland, FL'],
            ['name'=>'Rotonda West, FL'],
            ['name'=>'Ruskin, FL'],
            ['name'=>'Safety Harbor, FL'],
            ['name'=>'San Antonio, FL'],
            ['name'=>'Sanford, FL'],
            ['name'=>'Sanibel, FL'],
            ['name'=>'Sarasota, FL'],
            ['name'=>'Satellite Beach, FL'],
            ['name'=>'Sebastian, FL'],
            ['name'=>'Sebring, FL'],
            ['name'=>'Seffner, FL'],
            ['name'=>'Seminole, FL'],
            ['name'=>'Shalimar, FL'],
            ['name'=>'Sharpes, FL'],
            ['name'=>'Silver Springs, FL'],
            ['name'=>'Sneads, FL'],
            ['name'=>'Sopchoppy, FL'],
            ['name'=>'Sorrento, FL'],
            ['name'=>'South Bay, FL'],
            ['name'=>'Spring Hill, FL'],
            ['name'=>'Starke, FL'],
            ['name'=>'Stuart, FL'],
            ['name'=>'Tallahassee, FL'],
            ['name'=>'Tampa, FL'],
            ['name'=>'Tangerine, FL'],
            ['name'=>'Tarpon Springs, FL'],
            ['name'=>'Tavares, FL'],
            ['name'=>'Tavernier, FL'],
            ['name'=>'Thonotosassa, FL'],
            ['name'=>'Titusville, FL'],
            ['name'=>'Trenton, FL'],
            ['name'=>'Umatilla, FL'],
            ['name'=>'Valparaiso, FL'],
            ['name'=>'Valrico, FL'],
            ['name'=>'Venice, FL'],
            ['name'=>'Vernon, FL'],
            ['name'=>'Vero Beach, FL'],
            ['name'=>'Wabasso, FL'],
            ['name'=>'Waldo, FL'],
            ['name'=>'Wauchula, FL'],
            ['name'=>'Wausau, FL'],
            ['name'=>'Waverly, FL'],
            ['name'=>'Webster, FL'],
            ['name'=>'Welaka, FL'],
            ['name'=>'West Palm Beach, FL'],
            ['name'=>'Westville, FL'],
            ['name'=>'Wewahitchka, FL'],
            ['name'=>'White Springs, FL'],
            ['name'=>'Wildwood, FL'],
            ['name'=>'Williston, FL'],
            ['name'=>'Wimauma, FL'],
            ['name'=>'Windermere, FL'],
            ['name'=>'Winter Beach, FL'],
            ['name'=>'Winter Garden, FL'],
            ['name'=>'Winter Haven, FL'],
            ['name'=>'Winter Park, FL'],
            ['name'=>'Winter Springs, FL'],
            ['name'=>'Woodville, FL'],
            ['name'=>'Yalaha, FL'],
            ['name'=>'Yankeetown, FL'],
            ['name'=>'Yulee, FL'],
            ['name'=>'Zellwood, FL'],
            ['name'=>'Zephyrhills, FL'],
            ['name'=>'Zolfo Springs, FL'],
        ]);
    }
}
